const state={draft:[],db:JSON.parse(localStorage.getItem('moduleScanDb')||'[]')};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function parseTag(tag){let a=(tag||'').match(/(?:^|-)A(\d+)(?:-|$)/i),l=(tag||'').match(/(?:^|-)L(\d+)(?:-|$)/i);return{towerNo:a?'A'+a[1]:'',level:l?'L'+l[1]:''}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show-toast');setTimeout(()=>t.classList.remove('show-toast'),2500)}
const titles={upload:['Upload & Extract','Upload a module schedule photo and convert it into structured data.'],database:['Module Database','Search, filter and manage all saved module records.'],export:['Export Data','Download your module records for use in Excel.']};
$$('.nav').forEach(b=>b.onclick=()=>{ $$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active-page'));$('#'+b.dataset.page).classList.add('active-page');$('#pageTitle').textContent=titles[b.dataset.page][0];$('#pageSubtitle').textContent=titles[b.dataset.page][1];renderDb()});
$('#photoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;$('#preview').src=URL.createObjectURL(f);$('#previewWrap').classList.remove('hidden');$('#dropzone').classList.add('hidden')};
$('#removePhoto').onclick=()=>{$('#photoInput').value='';$('#previewWrap').classList.add('hidden');$('#dropzone').classList.remove('hidden')};
$('#extractBtn').onclick=()=>{if(!$('#photoInput').files[0]){toast('Please upload a photo first');return}state.draft=[{sl:'1',module:'',tag:'',towerNo:'',level:'',tower:''}];renderDraft();$('#reviewCard').classList.remove('hidden');$('#reviewCard').scrollIntoView({behavior:'smooth'})};
function rowHtml(r,i){return `<tr><td><input data-k="sl" data-i="${i}" value="${r.sl||''}"></td><td><input data-k="module" data-i="${i}" value="${r.module||''}"></td><td><input data-k="tag" data-i="${i}" value="${r.tag||''}"></td><td><input data-k="towerNo" data-i="${i}" value="${r.towerNo||''}" readonly></td><td><input data-k="level" data-i="${i}" value="${r.level||''}" readonly></td><td><input data-k="tower" data-i="${i}" value="${r.tower||''}"></td><td><button class="remove" data-remove="${i}">×</button></td></tr>`}
function renderDraft(){$('#draftTable tbody').innerHTML=state.draft.map(rowHtml).join('');$$('#draftTable input').forEach(inp=>inp.oninput=()=>{let r=state.draft[inp.dataset.i];r[inp.dataset.k]=inp.value;if(inp.dataset.k==='tag'){let p=parseTag(inp.value);r.towerNo=p.towerNo;r.level=p.level;renderDraft()}});$$('[data-remove]').forEach(b=>b.onclick=()=>{state.draft.splice(b.dataset.remove,1);renderDraft()})}
$('#addRow').onclick=()=>{state.draft.push({sl:String(state.draft.length+1),module:'',tag:'',towerNo:'',level:'',tower:''});renderDraft()};
$('#clearDraft').onclick=()=>{state.draft=[];renderDraft()};
$('#saveBtn').onclick=()=>{let added=0,dupe=0;state.draft.forEach(r=>{if(!r.tag)return;let exists=state.db.some(x=>x.towerNo===r.towerNo&&x.level===r.level&&x.tag===r.tag&&x.tower===r.tower);if(exists)dupe++;else{state.db.push({...r,saved:new Date().toLocaleString()});added++}});localStorage.setItem('moduleScanDb',JSON.stringify(state.db));toast(`Saved ${added} record(s)${dupe?`, skipped ${dupe} duplicate(s)`:''}`);renderDb()};
function renderDb(){let q=$('#searchInput').value?.toLowerCase()||'',a=$('#towerFilter').value?.toLowerCase()||'',l=$('#levelFilter').value?.toLowerCase()||'',t=$('#towerColFilter').value?.toLowerCase()||'';let rows=state.db.filter(r=>(!q||(r.tag+r.module).toLowerCase().includes(q))&&(!a||r.towerNo.toLowerCase().includes(a))&&(!l||r.level.toLowerCase().includes(l))&&(!t||r.tower.toLowerCase().includes(t)));$('#dbTable tbody').innerHTML=rows.map(r=>`<tr><td>${r.sl}</td><td>${r.module}</td><td>${r.tag}</td><td>${r.towerNo}</td><td>${r.level}</td><td>${r.tower}</td><td>${r.saved}</td><td><button class="remove" data-del="${state.db.indexOf(r)}">×</button></td></tr>`).join('');$$('[data-del]').forEach(b=>b.onclick=()=>{state.db.splice(b.dataset.del,1);localStorage.setItem('moduleScanDb',JSON.stringify(state.db));renderDb()});$('#totalRecords').textContent=state.db.length;$('#towerCount').textContent=new Set(state.db.map(r=>r.towerNo)).size;$('#levelCount').textContent=new Set(state.db.map(r=>r.level)).size}
['#searchInput','#towerFilter','#levelFilter','#towerColFilter'].forEach(id=>$(id).oninput=renderDb);
$('#clearDb').onclick=()=>{if(confirm('Delete all saved records?')){state.db=[];localStorage.removeItem('moduleScanDb');renderDb();toast('Database cleared')}};
$('#exportBtn').onclick=()=>{let cols=['Sl. Number','Module Details','Tag','Tower No.','Level','Tower','Saved'];let csv=[cols.join(','),...state.db.map(r=>[r.sl,r.module,r.tag,r.towerNo,r.level,r.tower,r.saved].map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='module_data.csv';a.click()};
renderDb();